In [27]:
# Importing the libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import random

from datetime import datetime

In [28]:
# Load the dataset
dataset = pd.read_csv(r'../data/input/raw/240624_validation_data.csv')

# Extract the time, forecasted demand and actual demand
time = dataset['time']
time = pd.to_datetime(time, utc=True)
forecast_demand = dataset['predicted heat']
actual_demand = dataset['delivered heat']

# Create a dataframe
df_data = pd.DataFrame({'time' : time, 'actual_demand': actual_demand, 'forecast_demand': forecast_demand})
df_data['hour']=time.dt.hour

In [29]:
# Select the date for which you want to extract the data
selected_date = '2023-04-03'

# Extract the data for the selected date
daily_date = df_data[df_data['time'].dt.date == pd.to_datetime(selected_date).date()].reset_index(drop=True)
daily_date = daily_date[['time', 'hour', 'actual_demand', 'forecast_demand']]
if(len(daily_date)==24):
    print('The selected date has 24 hours')
else:
    print('The selected date does not have 24 hours')

daily_date

The selected date has 24 hours

                        time  hour  actual_demand  forecast_demand
0  2023-04-03 00:00:00+00:00     0     115.450001       115.098197
1  2023-04-03 01:00:00+00:00     1     175.525003       138.890325
2  2023-04-03 02:00:00+00:00     2     304.204170       275.272401
3  2023-04-03 03:00:00+00:00     3     208.912505       191.269467
4  2023-04-03 04:00:00+00:00     4     251.229173       207.094822
5  2023-04-03 05:00:00+00:00     5     255.120837       203.753332
6  2023-04-03 06:00:00+00:00     6     201.050005       200.258381
7  2023-04-03 07:00:00+00:00     7     185.095836       187.718257
8  2023-04-03 08:00:00+00:00     8     138.179170       183.580818
9  2023-04-03 09:00:00+00:00     9     141.700001       165.749762
10 2023-04-03 10:00:00+00:00    10      98.695835       156.175397
11 2023-04-03 11:00:00+00:00    11      88.854169       143.394072
12 2023-04-03 12:00:00+00:00    12     102.208335       152.363284
13 2023-04-03 13:00:00+00:00    13     144.333335       171.437521
14 2023-04-03 14:00:00+00:00    14     121.033335       181.668571
15 2023-04-03 15:00:00+00:00    15     181.279170       192.249306
16 2023-04-03 16:00:00+00:00    16     181.800004       201.555549
17 2023-04-03 17:00:00+00:00    17     207.708337       220.129889
18 2023-04-03 18:00:00+00:00    18     160.400002       204.505700
19 2023-04-03 19:00:00+00:00    19     167.179170       180.921055
20 2023-04-03 20:00:00+00:00    20      79.304168       125.156652
21 2023-04-03 21:00:00+00:00    21     110.379169       135.779481
22 2023-04-03 22:00:00+00:00    22     111.491669       133.412958
23 2023-04-03 23:00:00+00:00    23     133.675002       137.074306

In [30]:
# Create a dataframe for heat_demand
heat_demand = daily_date

# Extract the timestamp
timestamp_str = heat_demand['time'][0]
timestamp_dt = datetime.strptime(str(timestamp_str), '%Y-%m-%d %H:%M:%S%z')

# Extract the date
formatted_date = timestamp_dt.strftime('%Y%m%d')

# add index t
t = [str(i) for i in range(1,25)]
heat_demand = heat_demand.drop(columns=['time','actual_demand', 'hour'])
heat_demand['t'] = t
heat_demand['forecast_demand'] = heat_demand['forecast_demand'].round(2)

# Reorder the columns
heat_demand = heat_demand[['t', 'forecast_demand']]
heat_demand = heat_demand.rename(columns={"forecast_demand": "heat_demand"})

heat_demand.to_csv(path_or_buf='../data/input/demands/heat_demand_' + formatted_date + '.csv', index = False)

In [31]:
# Erstellung eines Dummy-Datensatzes
heat_demand['heat_demand'] = heat_demand['heat_demand'] / 2

# Speichern des bearbeiteten DataFrame in eine CSV-Datei
heat_demand.to_csv(path_or_buf='../data/input/demands/heat_demand_dummy_' + formatted_date + '.csv', index=False)

In [45]:
# eins = pd.read_csv(r'../data/input/demands/heat_demand_20230403.csv')
# zwei = pd.read_csv(r'../data/input/demands/heat_demand_20230701.csv')
# drei = pd.read_csv(r'../data/input/demands/heat_demand_20230401.csv')

# combined_df = pd.concat([eins['t'], eins['heat_demand'], zwei['heat_demand'], drei['heat_demand']], axis=1)
# combined_df.columns = ['t','s1', 's2', 's3']
# combined_df.to_csv(path_or_buf='../data/input/demands/heat_demand_scenarios.csv', index=False)

---